package cc.sika.bookkeeping.pojo.po;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.io.Serializable;
import java.time.LocalDateTime;

@Builder
@AllArgsConstructor
@NoArgsConstructor
@TableName("sika_user")
@Data
public class SikaUser implements Serializable {
    @TableId(type= IdType.AUTO)
    private Long userId;
    /* login username */
    private String username;
    /*
    encipher password string,
    nullable, but it will be automatically generated same as the phone
    */
    private String password;
    /* user mobil phone number */
    private String phone;
    /* user email */
    private String email;
    /* unknown 0, male 1, female 2, default 0 */
    private Byte sex;
    /* avatar url link */
    private String avatar;
    /* show name */
    private String nickname;
    /* create time */
    private LocalDateTime createTime;
    /*
    founder's name,
    if it is register by user,
    it will be automatically generated by system be same as nickname
    */
    private String createBy;
    /* update time */
    private LocalDateTime updateTime;
    /* updater name */
    private String updateBy;
    /* record another information */
    private String remark;
}
