package cc.sika.bookkeeping.pojo.po;

import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.Builder;
import lombok.Data;

import java.io.Serializable;
import java.time.LocalDateTime;

@Data
@Builder
@TableName("sika_role")
public class SikaRole implements Serializable {
    /* role id, automatic increment */
    @TableId
    private Long roleId;

    /* role name */
    private String roleName;

    /* create time */
    private LocalDateTime createTime;

    /*
    founder's name,
    if it is register by user,
    it will be automatically generated by system be same as nickname
    */
    private String createBy;

    /* update time */
    private LocalDateTime updateTime;

    /* updater name */
    private String updateBy;
}
